language: node_js

node_js:
- '4.2'
script:
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then npm run-script generate; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run-script generate; fi
before_deploy:
  -  mkdir "output"; if compgen -G 'homolog*.json' > /dev/null; then for file in homolog*.json;do file=$(basename $file); mkdir "output/${file%.json}"; mv "$file" "output/${file%.json}/homology" ; done; fi
deploy:
  - provider: s3
    access_key_id: AKIAJUYQUJI4WTIHH7FQ
    skip_cleanup: true
    secret_access_key:
      secure: nCoq1CkB7edJuSpdCFtoJZnNKJy+bClrOACF6qT7kPWwljYrjNjTuLbK+QSkQxjAFVQB1/Q3yFp7opQcamETPo+N4Ok20V5qMuHUPObokHYpzl6mm1nmlwF70jl77ONWsZQBkawuSREZopdCp4X/OzROlJTNU/f2LWMhkvXalq5wOrALU1hbT4IAUT4l/aqrO3w81UoEWeVGrxj+9m1oOIcdmjtyDLL6oTODKZ3FtKDly55sXwdWP9KFDgWoVI4rcfil2wtEzpiZVm7wV/j7xRihsC/hb6h+fRft4fGxfXXj/x212xyA64Y6yKsMfL0jZvJw7r6MuRe9VdaxOlx39b9JOaJAezYRJCkVq3SOyp9n4oUh4/IiQC3a4E4g1dY4hHuZ2Dq3VQsDzM2lvGqUdt00X0Bzqsn7tubwNqNuKrjk9zjLDZUamXnTz2Th2/46B4jAvmbn84ZXs+zD0RWFTYsqvt68lW5wboanF1c5lyfk8/6vd2gBZEONPh74ZGq3wN8siNchtBuALqKiE5v9uZRvgQoerMQ1kZlL9H/RV+6lBYch8eRNTQHjYj3HswW4KIzo9jPdwCSQpDB+VtKI2wWIitPLu4FQvgGhWhXp/4vcftnu4I3gmPvuVamVgEEOc8YD8j/iCbd5ZQeFYwHFEcxzimQ8cwZhPwPp1qRJ0lo=
    bucket: test-gator
    region: us-east-1
    local-dir: output
    upload-dir: uploads
    acl: private
    on:
      branch: master
      repo: hirenj/node-compara2homology
  - provider: s3
    access_key_id: AKIAJUYQUJI4WTIHH7FQ
    skip_cleanup: true
    secret_access_key:
      secure: nCoq1CkB7edJuSpdCFtoJZnNKJy+bClrOACF6qT7kPWwljYrjNjTuLbK+QSkQxjAFVQB1/Q3yFp7opQcamETPo+N4Ok20V5qMuHUPObokHYpzl6mm1nmlwF70jl77ONWsZQBkawuSREZopdCp4X/OzROlJTNU/f2LWMhkvXalq5wOrALU1hbT4IAUT4l/aqrO3w81UoEWeVGrxj+9m1oOIcdmjtyDLL6oTODKZ3FtKDly55sXwdWP9KFDgWoVI4rcfil2wtEzpiZVm7wV/j7xRihsC/hb6h+fRft4fGxfXXj/x212xyA64Y6yKsMfL0jZvJw7r6MuRe9VdaxOlx39b9JOaJAezYRJCkVq3SOyp9n4oUh4/IiQC3a4E4g1dY4hHuZ2Dq3VQsDzM2lvGqUdt00X0Bzqsn7tubwNqNuKrjk9zjLDZUamXnTz2Th2/46B4jAvmbn84ZXs+zD0RWFTYsqvt68lW5wboanF1c5lyfk8/6vd2gBZEONPh74ZGq3wN8siNchtBuALqKiE5v9uZRvgQoerMQ1kZlL9H/RV+6lBYch8eRNTQHjYj3HswW4KIzo9jPdwCSQpDB+VtKI2wWIitPLu4FQvgGhWhXp/4vcftnu4I3gmPvuVamVgEEOc8YD8j/iCbd5ZQeFYwHFEcxzimQ8cwZhPwPp1qRJ0lo=
    bucket: beta-gator
    region: eu-west-1
    local-dir: output
    upload-dir: uploads
    acl: private
    on:
      branch: master
      repo: hirenj/node-compara2homology
