version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y sqlite3
      - npm install
  pre_build:
    commands:
      - compara_version=$(curl -Sss 'https://rest.ensembl.org/info/comparas?' -H 'Content-type:text/xml' | grep 'release' | sed -e 's/.*release="//' -e 's/".*//')
      - checkversion --fail-on-match --print-remote --remote 'http://rest.ensemblgenomes.org/info/eg_version' --regex '(\d+)' > ensembl_genomes_version.txt
      - testversion 'homology.json' --static "\$compara_version"
  build:
    commands:
      - echo "Running build step"
      - df -h
      - bash ./retrieve_data.sh $TARGETVERSION $WORKDIR
      - bash ./setup_sqlite.sh $WORKDIR
      - node index.js --version=$TARGETVERSION --database=$WORKDIR/compara.db --taxonomy=$BUILD_TAXONOMY
      - if [ ! -e dist ]; then mkdir dist; fi
      - mv homology*.json dist/
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist
