version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y sqlite3
      - npm install
  pre_build:
    commands:
      - compara_version=$(curl -Sss 'https://rest.ensembl.org/info/comparas?' -H 'Content-type:text/xml' | grep 'release' | sed -e 's/.*release="//' -e 's/".*//')
      - testversion 'homology.json' --static "\$compara_version"
  build:
    commands:
      - echo "Running build step"
      - df -h
      - curl 'ftp://ftp.ensembl.org/pub/release-${TARGETVERSION}/mysql/ensembl_compara_${TARGETVERSION}/seq_member.txt.gz' | gunzip | cut -f 1,2,4,5 - | fgrep 'Uniprot' > $WORKDIR/seq_member.txt
      - curl 'ftp://ftp.ensembl.org/pub/release-${TARGETVERSION}/mysql/ensembl_compara_${TARGETVERSION}/family_member.txt.gz' | gunzip > $WORKDIR/family_member.txt
      - curl 'ftp://ftp.ensembl.org/pub/release-${TARGETVERSION}/mysql/ensembl_compara_${TARGETVERSION}/homology_member.txt.gz' | gunzip > $WORKDIR/homology_member.txt
      - bash ./do_sqlite.sh $WORKDIR
      - node index.js --version=$TARGETVERSION --database=$WORKDIR/compara.db --taxonomy=$BUILD_TAXONOMY
      - if [ ! -e dist ]; then mkdir dist; fi
      - mv homology*.json dist/
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist