version: 0.1

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - compara_version=$(curl -Sss 'https://rest.ensembl.org/info/comparas?' -H 'Content-type:text/xml' | grep 'release' | sed -e 's/.*release="//' -e 's/".*//')
      - testversion 'homology.json' --static "\$compara_version"
  build:
    commands:
      - echo "Running build step"
      - curl 'ftp://ftp.ensembl.org/pub/release-${TARGETVERSION}/mysql/ensembl_compara_${TARGETVERSION}/seq_member.txt.gz' | gunzip | cut -f 1,2,4,5 - | fgrep 'Uniprot' > seq_member.txt
      - curl 'ftp://ftp.ensembl.org/pub/release-${TARGETVERSION}/mysql/ensembl_compara_${TARGETVERSION}/family_member.txt.gz' | gunzip > family_member.txt
      - sqlite3 compara.db < sqlcommands
      - node index.js --version=$TARGETVERSION --database=compara.db --taxonomy=$BUILD_TAXONOMY
      - if [ ! -e dist ]; then mkdir dist; fi
      - mv homology*.json dist/
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist